### ISSUE TITLE
Trouble installing on Ubuntu 

### ISSUE THREAD

**Issue by mckeankylej** [begriffs/haskell-vim-now#138]
When I try to install I get the following errors. http://lpaste.net/148457 I have been getting errors all night trying, and in my fixing of one error I could have broken another thing.

**Comment by begriffs** [comment]
It seems like you might have installed Stack as root at some point so that its directories are not accessible to your regular user. I'd suggest uninstalling stack and ghc, removing the `~/.stack` directory, reinstalling stack manually as described in [the docs](http://docs.haskellstack.org/en/stable/install_and_upgrade.html#ubuntu) and trying the haskell-vim-now installer again.

**Comment by mckeankylej** [comment]
I followed the installation instructors to the book. This being said stack still appears to be having permission issues. http://lpaste.net/148496

**Comment by begriffs** [comment]
Hmm, that's strange. Are you running the installer as user `kyle`? Which user owns the `/home/kyle/.local` and `/home/kyle/.local/bin` directories? What are their permissions.

**Comment by mckeankylej** [comment]
This is very interesting it appears that root owns .local/bin and its subdirectories http://lpaste.net/148506 Should I change this and if so how should I change it? Also see perms in the lpaste.

**Comment by begriffs** [comment]
Try changing ownership on the directory and its contents like this

```bash
sudo chown -R kyle /home/kyle/.local/bin
```

**Comment by mckeankylej** [comment]
That fixed the installation problems, I am having completely unrelated problems now, I am going to close this issue. Also thank you for figuring this problem out this was effecting some other things I have been trying to do :)

**Comment by begriffs** [comment]
Yay, glad it works!
