### ISSUE TITLE
PATH is set two times in .vimrc

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#147]
https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L69
https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L72

Why should you do this? First of all, we ***DO NOT*** need GHC paths, it's totally useless for stack projects (stack uses it's own paths for internal cmds like `stack ghci`, `stack exec`, `stack build`, `stack install` etc, and we should really only use them). More than that, I've made symlink to ~/.local/bin in haskell-vim-now directory just for the purpose to ***not*** call stack executable to obtain paths (it's slow and it's been run on *every* vim open!).
If user really need to set PATH to stack's paths, then he should use .bashrc/.zshrc or whatever shell is in use.

Anyway, there's no point to set it twice.

**Comment by begriffs** [comment]
The ghc path is needed for hdevtools which spawns a daemon. If hdevtools locates a ghc of the wrong version then it fails to check the haskell file for errors. On vim startup it finds the path of the currently stack-active ghc so that the first call to hdevtools will pick it up.

In the second call to set the path it may appear that it is overwriting the path but actually `stack path --bin-path` appends to the existing path and outputs the modified version, so this is keeping the old setting.

We could remove all this stack path finding stuff if we could go back to ghc-mod for everything. And I think ghc-mod fixed its vim support now so we can try!

**Comment by SimpleX91** [comment]
Yup, ghc-mod worked fine for me. It's better to use tools with full stack support.
Btw, `stack path --bin-path` already have this hvn-bin directory, so no need to use the first PATH assign.
