### ISSUE TITLE
consider delimitMate?

### ISSUE THREAD

**Issue by gspia** [begriffs/haskell-vim-now#255]
Earlier issues didn't seem to contain a discussion of
[Raimondi/delimitMate](https://github.com/Raimondi/delimitMate) or other similar tools (or then I just missed them)? Is some other plug doing the same thing?

    " auto insert closing delimits (quotes, parenthesis, brackets, etc.)
    Plug 'Raimondi/delimitMate'

**Comment by begriffs** [comment]
Sorry for the delayed response.

I've used auto paren/quote closers in the past and sometimes they felt convenient and other times not. You can always add new packages of your choice to plugins.vim as documented in https://github.com/begriffs/haskell-vim-now#adding-vim-plugins

Sound good?

**Comment by gspia** [comment]
No problems, sounds good & I followed this and got it working. Btw, is there a way to not use a plugin in the list (other than git cloning and commenting the file)?

**Comment by begriffs** [comment]
Hmm, actually I don't know of a way to remove a plugin. As a hack you might duplicate the Plug definition, and in your copy add a param:

```viml
Plug 'unwanted/annoying_plugin', { 'for': 'NEVERUSETHIS' }
```

Because no language will match NEVERUSETHIS it may disable the plugin.

Kind of a hack... closing this issue since you figured out your original question of adding a new plugin.
