### ISSUE TITLE
",hc" doesn't seem to do anything, ",ht" fails with "cannot guess type"

### ISSUE THREAD

**Issue by levinotik** [begriffs/haskell-vim-now#46]
Just ran the install script fresh and I seem to be having trouble with several commands. With code that doesn't compile, ",hc" outputs nothing. Also, for other functions defined (in the same file), ",ht" always reports that it "cannot guess type." happy is installed at .cabal/bin which is on my path.

**Comment by begriffs** [comment]
Can you tell me more about your system?

* What version of vim do you use?
* Which OS
* Which version of ghc-mod (Run `~/.haskell-vim-now/bin/ghc-mod --version`)
* Do you use a cabal sandbox in the project you're editing?

**Comment by levinotik** [comment]
Digging a bit deeper, I can see that i ",hc" is working fine in a new .hs file. It's in the context of a project (this specifically https://github.com/NICTA/course if it helps) that it has trouble.

**Comment by levinotik** [comment]
vim 7.4
mac yosemite 10.10.1
ghc-mod version 4.1.6 compiled by GHC 7.8.3
no sandbox in the project I'm editing

**Comment by begriffs** [comment]
Is it any file in the nicta course that causes the problem, or just certain files?

**Comment by levinotik** [comment]
Any file. Seems to be the case in a new cabal project as well, NICTA was just an example.

**Comment by levinotik** [comment]
[Here's](https://github.com/levinotik/ParseBird) a cabal project with a single file for which ",hl" and others seem to work, but ",hc" and ",ht" do not.

**Comment by begriffs** [comment]
I cloned the repo, did a cabal install, then `vim src/Text/ParseBird/Parsers.hs`.

I run `,hc` and it identifies a problem on line 12:

```
src/Text/ParseBird/Parsers.hs|12 col 8 error| Could not find module ‘Control.Monad.Identity’

It is a member of the hidden package ‘mtl-2.1.3.1’.

Perhaps you need to add ‘mtl’ to the build-depends in your .cabal file.Use -v to see a list of the files searched for.
```

At this point ',ht' does not work. So I add `mtl` to the cabal file and this fixes things - `,hc` starts identifying warnings and `,ht` shows the types. So it looks like bad imports break ghc-mod.

**Comment by begriffs** [comment]
Also remember the command `:Errors` will bring up a consolidated list of errors at the bottom of the screen so you don't have to scan through the file looking for marked lines.

**Comment by levinotik** [comment]
Thanks for the help @begriffs Still newish to Haskell and the tooling. I never had any problems even without mtl in my cabal file. Does that mean something is wrong with my sandbox and it's pulling it in from the global cabal depdencies?

**Comment by begriffs** [comment]
The hidden packages thing is a quirk of Cabal. A package might very well have been downloaded into your sandbox as the dependency of another package but to import it into your code you need to explicitly mention it in your cabal file. https://www.haskell.org/cabal/FAQ.html#hidden-packages-a

Let me know if adding `mtl` makes things work for you. If it does then we can close this issue and create a new wiki about runtime issues and explain this gotcha.

**Comment by levinotik** [comment]
I'm a bit confused still. That project builds fine for me even without mtl in my cabal file.

**Comment by begriffs** [comment]
True, same for me. if I do `cabal build` with the code exactly as it exists in the original repo it builds without complaint. Interestingly it also builds when I remove this line

```diff
@@ -9,8 +9,6 @@ import Control.Applicative

 import Control.Monad

-import Control.Monad.Identity (Identity)
-
 parse rule = Parsec.parse rule "(source)"

 -- | Parse hashtags
```

Once the line is removed the type checking `,ht` works properly too. Apparently the code does not actually use `Control.Monad.Identity` hence it never triggers a problem for an actual build. However `ghc-mod` must be naively trying to import it and cannot because it is in a hidden package.

This does seem annoying since the program builds fine...Not sure how to get around the problem other than clean up unnecessary imports.

**Comment by levinotik** [comment]
Oh interesting, thanks! I removed it, but still can't seem to get `,ht` to work..still getting `cannot guess type`

**Comment by begriffs** [comment]
Hmm this is getting strange. Do you remember how you installed Haskell? Was it the Haskell Platform or some other installer? You might just have a lot of packages floating around in various parts of your system. Cabal has a global and user package database on your system which might have conflicting versions of packages. As a rule of Haskell hygiene I no longer ever install packages to the global or user dbs. I use sandboxes for every little thing I do because it keeps projects from contaminating each other which has always kind of been a problem for cabal.

The vim type finder and file checker functionality works for me and many other people so I'm thinking the next step for debugging it on your computer would be to uninstall haskell, cabal, and all your cabal databases and reinstall. Then create a cabal sandbox for this example project and try things again. I know it seems drastic but it might prevent other build problems in the future.

If you had previously installed the OS X Haskell Platform there should be an uninstaller at `/Library/Haskell/bin/uninstall-hs`. I'd recommend reinstalling using a more focused tool like https://ghcformacosx.github.io which avoids filling your global db with superfluous libraries.

Now all this said, I do wish I knew what exactly is breaking ghc-mod.

**Comment by levinotik** [comment]
ghcformacosx is what I currently have installed, but something must've gotten messed up. Should I also delete my cabal folder if I want to start fresh? Thanks again for all your help with this!

**Comment by levinotik** [comment]
I uninstalled everything and installed the latest ghcformacosx and everything seems to work now. Thanks for your help and for this awesome vim IDE. Makes vim a real pleasure to work with!
