### ISSUE TITLE
error when building docker image

### ISSUE THREAD

**Issue by huiwang** [begriffs/haskell-vim-now#62]
---> Running in 00f407df5098
/bin/sh: 1: /install.sh: Permission denied
The command '/bin/sh -c /install.sh && rm -r /root/.cabal' returned a non-zero code: 126

I get the above error when trying to build docker image as explained
docker build -t haskell-vim .

any ideas ?

**Comment by huiwang** [comment]
This error is resolved by giving the exec rights to the install.sh
chmod +x install.sh

**Comment by paullamar3** [comment]
I ran into the same issue. I updated my Dockerfile as follows:

```
FROM haskell:7.8

# install vim tooling
RUN apt-get update \
 && apt-get install -y git vim curl build-essential wget tmux\
      # for vim extensions
      exuberant-ctags libcurl4-openssl-dev \
 && apt-get clean

# Haskell Vim setup
ADD https://raw.githubusercontent.com/begriffs/haskell-vim-now/master/install.sh /install.sh
RUN chmod +x /install.sh
RUN /install.sh && rm -r /root/.cabal
```

Note that besides adding the `chmod` I also added the `wget` package (as this stopped some warning messages that popped up when hoogle was being built) and the `tmux` package (because, `tmux` is awesome in a development environment).

Everything seems to be working well now.

> ASIDE: Thank you Joe Nelson for putting this project together. Just reading through the `install.sh` file has helped me learn about both Vim and Haskell (which is good as I'm relatively new to both).

**Comment by gregwebs** [comment]
this is fixed and can be closed
